# 仅限本机演示：不要直接用于生产
listener 1883 127.0.0.1
allow_anonymous false
password_file ./passwd
acl_file ./acl.example
persistence false
retain_available false
connection_messages true
log_type error
log_type warning
log_type notice
log_dest stdout
max_packet_size 1100000
message_size_limit 1100000
